name: Backend Docker Image CI

on:
  push:
    branches: [ "master", "reactTestingDev" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker images
      run: |
        cd project
        docker build . --file Dockerfile --tag prime-finder
        cd ..
        cd prime-app
        docker build . --file Dockerfile --tag prime-react-ui

    - name: pushing the docker image 
      run: |
        docker tag prime-finder howechristopher/prime-finder
        docker push howechristopher/prime-finder
        docker tag prime-react-ui howechristopher/prime-react-ui
        docker push howechristopher/prime-react-ui

